"""Everyday development commands that the dogma Bash guards must let through
(data only, never executed). Rows: (command, directory); "X" = project whose
DOGMA-PERMISSIONS.md allows everything, "N" = no permissions file, "W" = like X but
below a path that contains a /home/<user> segment.
"""

# fmt: off
EVERYDAY = (
    ("ls -la", "N"),
    ("ls ~", "N"),
    ("pwd && ls -la src", "N"),
    ("git status", "N"),
    ("git status -s && git diff --stat", "N"),
    ("git log --oneline -10", "N"),
    ("git log --format='%h %s' -5 | head -3", "N"),
    ("git diff HEAD~1 -- plugins/dogma/scripts/delete-guard.py", "N"),
    ("git show --stat HEAD", "N"),
    ("git branch -a", "N"),
    ("git remote", "N"),
    ("git fetch origin", "N"),
    ("git stash list", "N"),
    ("git rm --cached notes.txt", "N"),
    ("git reset HEAD notes.txt", "N"),
    ("git restore --staged notes.txt", "N"),
    ("git add notes.txt && git commit -m 'docs: notes' && git push origin main", "X"),
    ("git commit -m \"fix: rm stale entries and drop the secret sauce\"", "X"),
    ("grep -rn 'TODO' src/ | head -20", "N"),
    ("rg -n 'def main' --type py", "N"),
    ("find . -name '*.py' -newer setup.py", "N"),
    ("find . -type f -name '*.md' | wc -l", "N"),
    ("cat README.md", "N"),
    ("head -50 src/main.py", "N"),
    ("sed -n '1,40p' plugins/dogma/scripts/file-protection.sh", "N"),
    ("jq '.version' package.json", "N"),
    ("wc -l src/*.py", "N"),
    ("mkdir -p build/out && cp src/a.txt build/out/", "N"),
    ("touch build/.keep", "N"),
    ("mv build/a.txt build/b.txt", "N"),
    ("cp -r src /tmp/backup-src", "N"),
    ("tar czf /tmp/src.tgz src", "N"),
    ("python3 -m pytest -q tests/", "N"),
    ("python3 -I scripts/check.py --verbose", "N"),
    ("python3 -c 'print(1 + 1)'", "N"),
    ("node -e 'console.log(JSON.stringify({a: 1}))'", "N"),
    ("node --version && npm --version", "N"),
    ("npm test", "N"),
    ("npm run build", "N"),
    ("npm ci", "N"),
    ("npx tsc --noEmit", "N"),
    ("make test", "N"),
    ("bash plugins/dogma/scripts/test-delete-guard.sh", "N"),
    ("shellcheck scripts/*.sh", "N"),
    ("echo $HOME", "N"),
    ("echo \"done: $(date +%H:%M)\"", "N"),
    ("printf '%s\\n' a b > list.txt", "N"),
    ("date '+%Y-%m-%d %H:%M:%S'", "N"),
    ("which python3 && python3 --version", "N"),
    ("du -sh src", "N"),
    ("diff -u a.txt b.txt", "N"),
    ("curl -fsS https://example.com/api/status", "N"),
    ("gh pr view 12 --json title,state", "N"),
    ("gh pr create --title 'fix: guard' --body 'Removes stale rm handling'", "N"),
    ("tmux list-sessions", "N"),
    ("rm -rf build dist", "X"),
    ("rm -f build/out/a.o", "X"),
    ("find . -name '*.pyc' -delete", "X"),
    ("git clean -fdx", "X"),
    ("D=$(mktemp -d) && cp src/a.txt \"$D\" && rm -rf \"$D\"", "X"),
    ("cd src && ls && cd ..", "N"),
    ("for f in src/*.py; do python3 -m py_compile \"$f\"; done", "N"),
    ("if [ -f setup.py ]; then echo yes; fi", "N"),
    ("cat <<'EOF' > notes.md\n# Notes\nnever rm -rf the home\nEOF", "N"),
    ("ls ~/.ssh", "N"),
    ("cat .env.example", "N"),
    ("git stash pop", "N"),
    ("cp report.pdf ~/", "N"),
    ("cp report.pdf ~", "N"),
    ("mv a.txt ~/git/", "N"),
    ("mv ~/Downloads/f.pdf ~/Documents/", "N"),
    ("cp -r build ~/Documents", "N"),
    ("cp -t ~/Documents report.pdf notes.md", "N"),
    ("install -m 755 tool.sh ~/git/", "N"),
    ("mv -t ~/Documents a.pdf b.pdf", "N"),
    ("mv --target-directory ~/Documents a.pdf", "N"),
    ("mv --target-directory=$HOME/Documents a.pdf", "N"),
    ("cp -rf src dst", "N"),
    ("mv -fv a.txt b.txt", "N"),
    ("cp -at ~/Documents report.pdf", "N"),
    ("cp -rt /tmp/out src", "N"),
    ("mv -vt ~/Documents a.pdf", "N"),
    ("install -Dm644 a.conf build/etc/a.conf", "N"),
    ("install -d ~/Documents/new", "N"),
    ("ln -sf ../a.txt b.txt", "N"),
    ("rsync -av src/ /tmp/backup/", "N"),
    ("rsync -av report.pdf ~/Documents/", "N"),
    ("rm homelink", "X"),
    ("rm -f ./homelink", "X"),
    ("unlink homelink", "X"),
    ("rm ~/Documents/link.pdf", "X"),
    ("mv homelink /tmp/moved-link", "X"),
    ("rsync -a --no-perms --info=progress2 --cc=xxh128 src/ /tmp/backup/", "N"),
    ("rsync -avz --exclude node_modules -e ssh src/ /tmp/backup/", "N"),
    ("POSIXLY_CORRECT=1 cp -r src /tmp/out", "N"),
    ("rm -rf .git/hooks/../../dist", "X"),
    ("env FOO=1 rm -rf build", "X"),
    ("env -C sub rm -rf dist", "X"),
    ("sudo -u www-data rm -rf /tmp/cache-x", "X"),
    ("env -S 'FOO=1 BAR=2' make test", "N"),
    ("env -S 'make\\_-j4\\_test'", "N"),
    ("tmux new-session -d -s build 'make test'", "N"),
    ("tmux new-window 'npm run dev'", "N"),
    ("systemd-run --user --scope make", "N"),
    ("systemd-run --user --scope rm -rf build", "X"),
    ("su -c 'make test' builder", "N"),
    ("bwrap --ro-bind / / --dev /dev true", "N"),
    # W: allow-all project below a path with a /home/<user> segment (the cwd is no target)
    ("rsync -a --delete build/ out/", "W"),
    ("rsync -av --delete-after src/ /tmp/backup/", "W"),
    ("chmod -R u+w build", "W"),
    ("tar --remove-files -czf build.tgz build", "W"),
    ("rm -rf build", "W"),
    ("cd sub && rm -rf dist", "W"),
    ("for f in *.pdf; do cp \"$f\" ~/Documents/; done", "N"),
)
# fmt: on
