#!/usr/bin/env python3
"""Changelog fragments and release tooling for the plugin marketplace.

Usage:
  release.py <plugin> [--dry-run] [--month YYYY-MM]   release one plugin from its fragments
  release.py --root [--dry-run]                        regenerate the root CHANGELOG.md only
  release.py --check                                   validate all fragments and changelogs

Common option:
  --repo PATH   repository root to operate on (default: env RELEASE_REPO_ROOT,
                else the repository this script lives in)

Fragments live in plugins/<plugin>/changelog.d/<slug>.md, see changelog.d/README.md.
The script never commits; it prints the changed files and a suggested commit subject.
"""

import argparse
import datetime
import json
import os
import re
import subprocess
import sys

SECTIONS = ["Added", "Changed", "Deprecated", "Removed", "Fixed", "Security"]
BUMPS = ["patch", "minor", "major"]
FRAGMENT_NAME_RE = re.compile(r"^(?:\d+-)?[a-z0-9]+(?:-[a-z0-9]+)*\.md$")
HEADING_RE = re.compile(r"^(#{1,6})\s+(.*?)\s*$")
MONTH_RE = re.compile(r"^(\d{4})-(\d{2})$")
VERSION_HEADING_RE = re.compile(r"^v(\d+)(?:\.(\d+))?(?:\.(\d+))?$")
SEMVER_RE = re.compile(r"^(\d+)\.(\d+)\.(\d+)$")
SUMMARY_ITEM_MAX = 60

PLUGIN_INTRO = (
    "Changelog of the {plugin} plugin. Newest first. Months group releases; no day dates. "
    "Entries are written by scripts/changelog/release.py from changelog.d/ fragments."
)
ROOT_INTRO = (
    "Consolidated changelog of all plugins in this marketplace. Newest first. Months group "
    "releases; no day dates. This file is generated by scripts/changelog/release.py from "
    "plugins/*/CHANGELOG.md - never edit it by hand."
)


class ReleaseError(Exception):
    """A validation or refusal problem; message names the file and the problem."""


# ---------------------------------------------------------------- helpers


def rel(repo, path):
    return os.path.relpath(path, repo)


def read_text(path):
    with open(path, encoding="utf-8") as fh:
        return fh.read()


def write_text(path, text):
    with open(path, "w", encoding="utf-8", newline="\n") as fh:
        fh.write(text)


def vstr(version):
    return "v" + ".".join(str(n) for n in version)


def plugin_names(repo):
    base = os.path.join(repo, "plugins")
    if not os.path.isdir(base):
        return []
    return sorted(
        name
        for name in os.listdir(base)
        if os.path.isfile(os.path.join(base, name, "plugin.yaml"))
    )


# ---------------------------------------------------------------- fragments


def parse_fragment(path, display):
    """Return (bump, {section: [bullet_lines, ...]}) or raise ReleaseError."""
    name = os.path.basename(path)
    if not FRAGMENT_NAME_RE.match(name):
        raise ReleaseError(
            f"{display}: invalid file name (expected [NNN-]lowercase-slug.md, "
            "letters/digits separated by single hyphens)"
        )
    lines = [line.rstrip() for line in read_text(path).splitlines()]
    if len(lines) < 3 or lines[0] != "---" or lines[2] != "---":
        raise ReleaseError(f"{display}: missing front matter (expected '---', 'bump: <level>', '---' as first three lines)")
    match = re.match(r"^bump:\s*(\S+)$", lines[1])
    if not match:
        raise ReleaseError(f"{display}:2: front matter must contain exactly 'bump: patch|minor|major'")
    bump = match.group(1)
    if bump not in BUMPS:
        raise ReleaseError(f"{display}:2: unknown bump '{bump}' (allowed: patch, minor, major)")

    sections = {}
    current = None
    for lineno, line in enumerate(lines[3:], start=4):
        if not line:
            continue
        heading = HEADING_RE.match(line)
        if heading:
            level, title = heading.groups()
            if level != "###" or title not in SECTIONS:
                raise ReleaseError(
                    f"{display}:{lineno}: unknown section heading '{line}' "
                    f"(allowed: '### ' + one of {', '.join(SECTIONS)})"
                )
            if title in sections:
                raise ReleaseError(f"{display}:{lineno}: duplicate section '{title}'")
            current = title
            sections[current] = []
            continue
        if current is None:
            raise ReleaseError(f"{display}:{lineno}: text before the first section heading")
        if line.startswith("- ") and line[2:].strip():
            sections[current].append([line])
        elif line.startswith("  ") and line.strip() and sections[current]:
            sections[current][-1].append(line)
        else:
            raise ReleaseError(
                f"{display}:{lineno}: expected a bullet '- text' or a continuation line indented by 2 spaces"
            )
    if not sections:
        raise ReleaseError(f"{display}: no section found (need at least one '### <Section>' with a bullet)")
    for title, bullets in sections.items():
        if not bullets:
            raise ReleaseError(f"{display}: section '{title}' is empty (needs at least one bullet)")
    return bump, sections


def collect_fragments(repo, plugin):
    """Return (list of (path, bump, sections), list of error messages)."""
    directory = os.path.join(repo, "plugins", plugin, "changelog.d")
    if not os.path.isdir(directory):
        return [], []
    fragments, errors = [], []
    for name in sorted(os.listdir(directory)):
        path = os.path.join(directory, name)
        if name == "README.md" or name.startswith(".") or not os.path.isfile(path):
            continue
        try:
            bump, sections = parse_fragment(path, rel(repo, path))
            fragments.append((path, bump, sections))
        except ReleaseError as exc:
            errors.append(str(exc))
    return fragments, errors


def merge_fragments(fragments):
    merged = {}
    for _path, _bump, sections in fragments:
        for title, bullets in sections.items():
            merged.setdefault(title, []).extend(bullets)
    return [(title, [line for bullet in merged[title] for line in bullet]) for title in SECTIONS if title in merged]


def highest_bump(fragments):
    return max((bump for _p, bump, _s in fragments), key=BUMPS.index)


def bump_version(version, level):
    major, minor, patch = version
    if level == "major":
        return (major + 1, 0, 0)
    if level == "minor":
        return (major, minor + 1, 0)
    return (major, minor, patch + 1)


def summarize(fragments):
    parts = []
    for _path, _bump, sections in fragments:
        first = next((sections[t][0] for t in SECTIONS if t in sections), None)
        if first is None:
            continue
        text = " ".join(part.strip() for part in first)[2:].strip().rstrip(".")
        if len(text) > SUMMARY_ITEM_MAX:
            cut = text[: SUMMARY_ITEM_MAX - 3]
            if " " in cut:
                cut = cut[: cut.rfind(" ")]
            text = cut.rstrip(" ,;:-") + "..."
        parts.append(text)
    return ", ".join(parts)


# ---------------------------------------------------------------- version files


def read_versions(repo, plugin):
    yaml_path = os.path.join(repo, "plugins", plugin, "plugin.yaml")
    json_path = os.path.join(repo, "plugins", plugin, ".claude-plugin", "plugin.json")
    for path in (yaml_path, json_path):
        if not os.path.isfile(path):
            raise ReleaseError(f"{rel(repo, path)}: version file missing")
    yaml_text = read_text(yaml_path)
    yaml_hits = re.findall(r"^version:\s*[\"']?([^\"'\s]+)[\"']?\s*$", yaml_text, re.M)
    if len(yaml_hits) != 1:
        raise ReleaseError(f"{rel(repo, yaml_path)}: expected exactly one 'version:' line, found {len(yaml_hits)}")
    json_text = read_text(json_path)
    try:
        json_version = json.loads(json_text).get("version")
    except ValueError as exc:
        raise ReleaseError(f"{rel(repo, json_path)}: invalid JSON ({exc})") from exc
    if len(re.findall(r'"version"\s*:\s*"[^"]*"', json_text)) != 1:
        raise ReleaseError(f"{rel(repo, json_path)}: expected exactly one \"version\" field")
    if yaml_hits[0] != json_version:
        raise ReleaseError(
            f"version files out of sync: {rel(repo, yaml_path)} has {yaml_hits[0]}, "
            f"{rel(repo, json_path)} has {json_version} - fix them before releasing"
        )
    match = SEMVER_RE.match(yaml_hits[0])
    if not match:
        raise ReleaseError(f"{rel(repo, yaml_path)}: version '{yaml_hits[0]}' is not X.Y.Z")
    version = tuple(int(n) for n in match.groups())
    return version, (yaml_path, yaml_text), (json_path, json_text)


def updated_version_files(yaml_file, json_file, new):
    new_str = ".".join(str(n) for n in new)
    yaml_path, yaml_text = yaml_file
    json_path, json_text = json_file
    yaml_new = re.sub(r"^(version:\s*[\"']?)[^\"'\s]+", lambda m: m.group(1) + new_str, yaml_text, count=1, flags=re.M)
    json_new = re.sub(r'("version"\s*:\s*")[^"]*(")', lambda m: m.group(1) + new_str + m.group(2), json_text, count=1)
    return [(yaml_path, yaml_new), (json_path, json_new)]


# ---------------------------------------------------------------- month


def parse_git_date_month(value):
    """Return YYYY-MM from a git-style date string, or None if not understood."""
    value = value.strip()
    # git internal format: "@1759433465 +0200" or "1759433465 +0200"
    match = re.match(r"^@?(\d{9,11})(?:\s+([+-])(\d{2})(\d{2}))?$", value)
    if match:
        offset = datetime.timedelta(0)
        if match.group(2):
            offset = datetime.timedelta(hours=int(match.group(3)), minutes=int(match.group(4)))
            if match.group(2) == "-":
                offset = -offset
        moment = datetime.datetime.fromtimestamp(int(match.group(1)), datetime.timezone(offset))
        return f"{moment.year:04d}-{moment.month:02d}"
    # ISO 8601 / git "2026-10-02 21:31:05 +0200" / "2026.10.02" / "2026/10/02"
    match = re.match(r"^(\d{4})[-./](\d{1,2})[-./](\d{1,2})(?:$|[T\s])", value)
    if match:
        year, month, day = (int(n) for n in match.groups())
    else:
        # RFC 2822 "Fri, 2 Oct 2026 21:31:05 +0200" and git default "Fri Oct 2 21:31:05 2026 +0200"
        months = ["jan", "feb", "mar", "apr", "may", "jun", "jul", "aug", "sep", "oct", "nov", "dec"]
        tokens = re.findall(r"[A-Za-z]+|\d+", value)
        month = next((months.index(t[:3].lower()) + 1 for t in tokens if t[:3].lower() in months), None)
        year = next((int(t) for t in tokens if len(t) == 4 and t.isdigit()), None)
        if month is None or year is None:
            return None
        day = 1
    try:
        datetime.date(year, month, day)
    except ValueError:
        return None
    return f"{year:04d}-{month:02d}"


def resolve_month(cli_month):
    if cli_month:
        match = MONTH_RE.match(cli_month)
        if not match or not 1 <= int(match.group(2)) <= 12:
            raise ReleaseError(f"--month '{cli_month}' is not a valid YYYY-MM")
        return cli_month, "--month"
    for var in ("GIT_COMMITTER_DATE", "GIT_AUTHOR_DATE"):
        value = os.environ.get(var, "").strip()
        if value:
            month = parse_git_date_month(value)
            if month is None:
                raise ReleaseError(f"{var}='{value}' is not a date format this script understands; use --month YYYY-MM")
            return month, var
    today = datetime.date.today()
    return f"{today.year:04d}-{today.month:02d}", "today"


# ---------------------------------------------------------------- plugin changelog model


def parse_changelog(text, display):
    """Parse a plugin CHANGELOG.md into (intro, entries).

    entry = {"month": "YYYY-MM", "version": (M, m) or (M, m, p), "sections": [(title, [lines])]}
    Headings are recognized by their text, not their depth; a section heading belongs to the
    nearest version node above it (patch, or minor for coarse historical entries).
    """
    lines = text.splitlines()
    intro_lines = []
    entries = []
    month = major = minor = None
    node = None  # entry receiving sections
    section = None  # (title, lines) receiving content
    seen_heading = False
    for lineno, raw in enumerate(lines, start=1):
        line = raw.rstrip()
        heading = HEADING_RE.match(line)
        if not heading:
            if not seen_heading:
                intro_lines.append(line)
            elif section is not None:
                section[1].append(line)
            elif line.strip():
                raise ReleaseError(f"{display}:{lineno}: text outside a section: '{line}'")
            continue
        seen_heading = True
        title = heading.group(2)
        section = None
        if MONTH_RE.match(title):
            month, major, minor, node = title, None, None, None
            continue
        version = VERSION_HEADING_RE.match(title)
        if version:
            nums = tuple(int(n) for n in version.groups() if n is not None)
            if month is None:
                raise ReleaseError(f"{display}:{lineno}: version heading '{title}' before any month heading")
            if len(nums) == 1:
                major, minor, node = nums, None, None
            elif len(nums) == 2:
                if major != nums[:1]:
                    raise ReleaseError(f"{display}:{lineno}: '{title}' is not under its major heading v{nums[0]}")
                minor = nums
                node = {"month": month, "version": nums, "sections": []}
                entries.append(node)
            else:
                if minor != nums[:2]:
                    raise ReleaseError(
                        f"{display}:{lineno}: '{title}' is not under its minor heading v{nums[0]}.{nums[1]}"
                    )
                node = {"month": month, "version": nums, "sections": []}
                entries.append(node)
            continue
        if title in SECTIONS:
            if node is None:
                raise ReleaseError(f"{display}:{lineno}: section '{title}' without a version heading above it")
            section = (title, [])
            node["sections"].append(section)
            continue
        raise ReleaseError(f"{display}:{lineno}: unknown heading '{line}'")

    cleaned = []
    seen = set()
    for entry in entries:
        sections = []
        for title, body in entry["sections"]:
            while body and not body[0].strip():
                body.pop(0)
            while body and not body[-1].strip():
                body.pop()
            if body:
                sections.append((title, body))
        if len(entry["version"]) == 2 and not sections:
            continue  # bare minor heading that only groups patch versions
        key = (entry["month"], entry["version"]) if len(entry["version"]) == 2 else entry["version"]
        if key in seen:
            raise ReleaseError(f"{display}: version {vstr(entry['version'])} appears twice")
        seen.add(key)
        if not sections:
            raise ReleaseError(f"{display}: version {vstr(entry['version'])} has no non-empty section")
        cleaned.append({"month": entry["month"], "version": entry["version"], "sections": sections})
    while intro_lines and not intro_lines[-1].strip():
        intro_lines.pop()
    while intro_lines and not intro_lines[0].strip():
        intro_lines.pop(0)
    return "\n".join(intro_lines), cleaned


def render_entries(entries, offset):
    """Render entries as heading tree; offset shifts every heading level."""
    out = []

    def heading(level, text):
        out.append("#" * (level + offset) + " " + text)
        out.append("")

    def body(sections, level):
        for title, lines in sections:
            heading(level, title)
            out.extend(lines)
            out.append("")

    months = sorted({e["month"] for e in entries}, reverse=True)
    for month in months:
        if offset == 0:
            heading(1, month)
        in_month = [e for e in entries if e["month"] == month]
        for major in sorted({e["version"][0] for e in in_month}, reverse=True):
            heading(2, f"v{major}")
            in_major = [e for e in in_month if e["version"][0] == major]
            for minor in sorted({e["version"][1] for e in in_major}, reverse=True):
                heading(3, f"v{major}.{minor}")
                in_minor = [e for e in in_major if e["version"][1] == minor]
                for coarse in [e for e in in_minor if len(e["version"]) == 2]:
                    body(coarse["sections"], 4)
                patches = sorted((e for e in in_minor if len(e["version"]) == 3), key=lambda e: e["version"], reverse=True)
                for entry in patches:
                    heading(4, vstr(entry["version"]))
                    body(entry["sections"], 5)
    return out


def render_plugin_changelog(intro, entries):
    out = [intro, ""] + render_entries(entries, 0)
    while out and not out[-1]:
        out.pop()
    return "\n".join(out) + "\n"


# ---------------------------------------------------------------- root changelog


def existing_root_order(text):
    """Return {month: [plugin, ...]} in the order the current root file lists them."""
    order = {}
    month = None
    for line in text.splitlines():
        match = re.match(r"^# (\d{4}-\d{2})\s*$", line)
        if match:
            month = match.group(1)
            order.setdefault(month, [])
            continue
        match = re.match(r"^## (\S+)\s*$", line)
        if match and month and not VERSION_HEADING_RE.match(match.group(1)):
            if match.group(1) not in order[month]:
                order[month].append(match.group(1))
    return order


def render_root(plugin_entries, previous_order, released=None):
    """plugin_entries: {plugin: entries}. previous_order: {month: [plugins]} from the old root.

    Inside a month, plugins keep the order of the previous root file (it records release
    recency); the plugin just released moves to the top of its month; plugins not yet listed
    follow, ordered by their newest version in that month (descending), ties alphabetical.
    """
    out = [ROOT_INTRO, ""]
    months = sorted({e["month"] for entries in plugin_entries.values() for e in entries}, reverse=True)
    for month in months:
        out += ["# " + month, ""]
        present = {p: [e for e in entries if e["month"] == month] for p, entries in plugin_entries.items()}
        present = {p: es for p, es in present.items() if es}
        known = [p for p in previous_order.get(month, []) if p in present]
        unknown = sorted(
            (p for p in present if p not in known),
            key=lambda p: (tuple(-n for n in max(pad(e["version"]) for e in present[p])), p),
        )
        ordered = known + unknown
        if released and released[1] == month and released[0] in ordered:
            ordered.remove(released[0])
            ordered.insert(0, released[0])
        for plugin in ordered:
            out += ["## " + plugin, ""]
            out += render_entries(present[plugin], 1)
    while out and not out[-1]:
        out.pop()
    return "\n".join(out) + "\n"


def pad(version):
    return tuple(version) + (-1,) * (3 - len(version))


def load_plugin_changelogs(repo, override=None):
    """Return {plugin: entries} for every plugin with a CHANGELOG.md (override: {plugin: entries})."""
    result = {}
    for plugin in plugin_names(repo):
        if override and plugin in override:
            result[plugin] = override[plugin]
            continue
        path = os.path.join(repo, "plugins", plugin, "CHANGELOG.md")
        if os.path.isfile(path):
            result[plugin] = parse_changelog(read_text(path), rel(repo, path))[1]
    return result


def build_root(repo, override=None, released=None):
    root_path = os.path.join(repo, "CHANGELOG.md")
    old = read_text(root_path) if os.path.isfile(root_path) else ""
    text = render_root(load_plugin_changelogs(repo, override), existing_root_order(old), released)
    return root_path, old, text


# ---------------------------------------------------------------- commands


def cmd_release(repo, plugin, dry_run, cli_month):
    if not os.path.isfile(os.path.join(repo, "plugins", plugin, "plugin.yaml")):
        raise ReleaseError(f"plugins/{plugin}: unknown plugin (no plugin.yaml)")
    fragments, errors = collect_fragments(repo, plugin)
    if errors:
        raise ReleaseError("invalid fragments, nothing written:\n  " + "\n  ".join(errors))
    if not fragments:
        raise ReleaseError(f"plugins/{plugin}/changelog.d: no fragments to release, nothing written")
    current, yaml_file, json_file = read_versions(repo, plugin)
    level = highest_bump(fragments)
    new = bump_version(current, level)
    month, month_source = resolve_month(cli_month)

    changelog_path = os.path.join(repo, "plugins", plugin, "CHANGELOG.md")
    if os.path.isfile(changelog_path):
        intro, entries = parse_changelog(read_text(changelog_path), rel(repo, changelog_path))
    else:
        intro, entries = PLUGIN_INTRO.format(plugin=plugin), []
    if any(e["version"] == new for e in entries):
        raise ReleaseError(f"{rel(repo, changelog_path)}: {vstr(new)} already exists")
    new_entry = {"month": month, "version": new, "sections": merge_fragments(fragments)}
    entries = [new_entry] + entries
    changelog_text = render_plugin_changelog(intro, entries)
    root_path, _old_root, root_text = build_root(repo, {plugin: entries}, (plugin, month))

    writes = updated_version_files(yaml_file, json_file, new)
    writes += [(changelog_path, changelog_text), (root_path, root_text)]
    deletes = [path for path, _b, _s in fragments]
    subject = f"{vstr(new)}: {summarize(fragments)}"

    prefix = "[dry-run] would " if dry_run else ""
    print(f"{plugin}: {vstr(current)} -> {vstr(new)} ({level}, highest of {len(fragments)} fragment(s))")
    print(f"month: {month} (from {month_source})")
    if dry_run:
        print("new entry:")
        for line in render_entries([new_entry], 0):
            print("    " + line if line else "")
    for path, _text in writes:
        print(f"{prefix}write  {rel(repo, path)}")
    for path in deletes:
        print(f"{prefix}delete {rel(repo, path)}")
    if not dry_run:
        for path, text in writes:
            write_text(path, text)
        for path in deletes:
            os.remove(path)
    print("changed files:")
    for path in sorted(rel(repo, p) for p in [w[0] for w in writes] + deletes):
        print("  " + path)
    print("suggested commit subject:")
    print("  " + subject)
    return 0


def cmd_root(repo, dry_run):
    root_path, old, text = build_root(repo)
    if old == text:
        print(f"{rel(repo, root_path)} is up to date")
        return 0
    if dry_run:
        print(f"[dry-run] would write {rel(repo, root_path)}")
    else:
        write_text(root_path, text)
        print(f"wrote {rel(repo, root_path)}")
    return 0


def changed_paths(repo):
    """Return changed paths (vs HEAD, plus untracked), or None when git is unavailable."""
    try:
        diff = subprocess.run(
            ["git", "-C", repo, "diff", "--name-only", "HEAD"], capture_output=True, text=True, check=True
        ).stdout
        untracked = subprocess.run(
            ["git", "-C", repo, "ls-files", "--others", "--exclude-standard"],
            capture_output=True,
            text=True,
            check=True,
        ).stdout
    except (OSError, subprocess.CalledProcessError):
        return None
    return [p for p in (diff + untracked).splitlines() if p]


def cmd_check(repo):
    errors, warnings = [], []
    counts = {}
    for plugin in plugin_names(repo):
        fragments, frag_errors = collect_fragments(repo, plugin)
        errors += frag_errors
        counts[plugin] = len(fragments) + len(frag_errors)
        path = os.path.join(repo, "plugins", plugin, "CHANGELOG.md")
        if os.path.isfile(path):
            try:
                parse_changelog(read_text(path), rel(repo, path))
            except ReleaseError as exc:
                errors.append(str(exc))
        try:
            read_versions(repo, plugin)
        except ReleaseError as exc:
            errors.append(str(exc))

    paths = changed_paths(repo)
    if paths is None:
        warnings.append("git not available or not a repository - skipped the changed-without-fragment check")
    else:
        ignored = re.compile(r"^plugins/[^/]+/(changelog\.d/.*|CHANGELOG\.md|plugin\.yaml|\.claude-plugin/plugin\.json)$")
        touched = sorted(
            {p.split("/")[1] for p in paths if p.startswith("plugins/") and p.count("/") >= 2 and not ignored.match(p)}
        )
        for plugin in touched:
            if plugin in counts and counts[plugin] == 0:
                warnings.append(f"plugins/{plugin}: files changed but no fragment in plugins/{plugin}/changelog.d/")

    if not errors:
        try:
            root_path, old, text = build_root(repo)
            if os.path.isfile(root_path) and old != text:
                warnings.append("CHANGELOG.md is out of date - run scripts/changelog/release.py --root")
        except ReleaseError as exc:
            errors.append(str(exc))

    for message in warnings:
        print("WARNING: " + message)
    for message in errors:
        print("ERROR: " + message, file=sys.stderr)
    if errors:
        return 1
    total = sum(counts.values())
    print(f"OK: {total} fragment(s) valid across {len(counts)} plugin(s)")
    return 0


def main(argv=None):
    parser = argparse.ArgumentParser(
        prog="release.py",
        description="Release a plugin from its changelog.d fragments (never commits).",
    )
    parser.add_argument("plugin", nargs="?", help="plugin name under plugins/")
    parser.add_argument("--dry-run", action="store_true", help="print what would happen, write nothing")
    parser.add_argument("--month", help="month of the new entry (YYYY-MM); default from GIT_COMMITTER_DATE, GIT_AUTHOR_DATE, today")
    parser.add_argument("--root", action="store_true", help="only regenerate the root CHANGELOG.md")
    parser.add_argument("--check", action="store_true", help="validate all fragments and changelogs")
    parser.add_argument("--repo", help="repository root (default: env RELEASE_REPO_ROOT or this script's repo)")
    args = parser.parse_args(argv)

    repo = args.repo or os.environ.get("RELEASE_REPO_ROOT") or os.path.dirname(
        os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
    )
    repo = os.path.abspath(repo)
    modes = sum(bool(x) for x in (args.plugin, args.root, args.check))
    if modes != 1:
        parser.error("give exactly one of: <plugin>, --root, --check")
    if args.month and not args.plugin:
        parser.error("--month only applies to a plugin release")
    if args.check and args.dry_run:
        parser.error("--check never writes; --dry-run is not needed")

    try:
        if args.check:
            return cmd_check(repo)
        if args.root:
            return cmd_root(repo, args.dry_run)
        return cmd_release(repo, args.plugin, args.dry_run, args.month)
    except ReleaseError as exc:
        print("ERROR: " + str(exc), file=sys.stderr)
        return 1


if __name__ == "__main__":
    sys.exit(main())
